### PR TITLE
CFE-3792: Changed python version requirement from >=3.6 to >=3.5

### PR DESCRIPTION
**Pull request by larsewi**
For cfbs to be python 3.5 compatible, its dependency cf-remote must also
be python 3.5 compatible.

Ticket: CFE-3792
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

### CODE REVIEW

**Comment by vpodzime** [comment]
@larsewi are you getting back to this? If not, please close this PR. (we got rid of the dependency in *cfbs*)

**Comment by vpodzime** [comment]
> @vpodzime IIRC it's basically waiting for your aramid-work.

I don't quite see why, but #36 is merged now so this is no longer blocked.

**Comment by olehermanse** [comment]
> I don't quite see why

@vpodzime Some libraries don't support python 3.5, most notably `cryptography`, I think.

**Comment by larsewi** [comment]
@olehermanse, @vpodzime, it looks like cf-remote the aramid work did the trick. I only had to remove f-strings, then 💚!

**Review by olehermanse — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
