### PR TITLE
SEC-242: Updated internal windows AMIs

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Review by larsewi — APPROVED** [review]
I ACKprove

**Review by craigcomstock — COMMENTED** [review]
thanks!

**Review by vpodzime — COMMENTED** [review]
Wish this had some explanation somewhere.

**Comment by olehermanse** [comment]
> Wish this had some explanation somewhere.

It does. The AMIs in the EC2 console have a description of what they contain, and there are some instructions here:

https://github.com/cfengine/mystiko/pull/101

**Pull request merged**
